# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import auction_pb2 as auction__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuctionServiceStub(object):
    """------------------------------------
    2. СЕРВІС
    ------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAuctions = channel.unary_unary(
                '/auction.AuctionService/GetAuctions',
                request_serializer=auction__pb2.Empty.SerializeToString,
                response_deserializer=auction__pb2.AuctionLots.FromString,
                _registered_method=True)
        self.CreateLot = channel.unary_unary(
                '/auction.AuctionService/CreateLot',
                request_serializer=auction__pb2.CreateLotRequest.SerializeToString,
                response_deserializer=auction__pb2.AuctionLot.FromString,
                _registered_method=True)
        self.PlaceBid = channel.unary_unary(
                '/auction.AuctionService/PlaceBid',
                request_serializer=auction__pb2.PlaceBidRequest.SerializeToString,
                response_deserializer=auction__pb2.AuctionLot.FromString,
                _registered_method=True)
        self.DeleteLot = channel.unary_unary(
                '/auction.AuctionService/DeleteLot',
                request_serializer=auction__pb2.DeleteLotRequest.SerializeToString,
                response_deserializer=auction__pb2.DeleteLotResponse.FromString,
                _registered_method=True)
        self.GetLotStatus = channel.unary_unary(
                '/auction.AuctionService/GetLotStatus',
                request_serializer=auction__pb2.GetLotStatusRequest.SerializeToString,
                response_deserializer=auction__pb2.LotStatusResponse.FromString,
                _registered_method=True)
        self.JoinAuction = channel.unary_unary(
                '/auction.AuctionService/JoinAuction',
                request_serializer=auction__pb2.LotIdUserRequest.SerializeToString,
                response_deserializer=auction__pb2.Empty.FromString,
                _registered_method=True)
        self.LeaveAuction = channel.unary_unary(
                '/auction.AuctionService/LeaveAuction',
                request_serializer=auction__pb2.LotIdUserRequest.SerializeToString,
                response_deserializer=auction__pb2.Empty.FromString,
                _registered_method=True)
        self.GetWinningsByUser = channel.unary_unary(
                '/auction.AuctionService/GetWinningsByUser',
                request_serializer=auction__pb2.UserRequest.SerializeToString,
                response_deserializer=auction__pb2.WinningsList.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/auction.AuctionService/Register',
                request_serializer=auction__pb2.AuthRequest.SerializeToString,
                response_deserializer=auction__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/auction.AuctionService/Login',
                request_serializer=auction__pb2.AuthRequest.SerializeToString,
                response_deserializer=auction__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.GetBidsByUser = channel.unary_unary(
                '/auction.AuctionService/GetBidsByUser',
                request_serializer=auction__pb2.UserRequest.SerializeToString,
                response_deserializer=auction__pb2.BidsList.FromString,
                _registered_method=True)


class AuctionServiceServicer(object):
    """------------------------------------
    2. СЕРВІС
    ------------------------------------

    """

    def GetAuctions(self, request, context):
        """Аукціони
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceBid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLotStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinAuction(self, request, context):
        """💡 Методи для відстеження присутності
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveAuction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWinningsByUser(self, request, context):
        """💡 НОВЕ: Отримання виграних лотів
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Користувачі
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBidsByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuctionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAuctions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuctions,
                    request_deserializer=auction__pb2.Empty.FromString,
                    response_serializer=auction__pb2.AuctionLots.SerializeToString,
            ),
            'CreateLot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLot,
                    request_deserializer=auction__pb2.CreateLotRequest.FromString,
                    response_serializer=auction__pb2.AuctionLot.SerializeToString,
            ),
            'PlaceBid': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBid,
                    request_deserializer=auction__pb2.PlaceBidRequest.FromString,
                    response_serializer=auction__pb2.AuctionLot.SerializeToString,
            ),
            'DeleteLot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLot,
                    request_deserializer=auction__pb2.DeleteLotRequest.FromString,
                    response_serializer=auction__pb2.DeleteLotResponse.SerializeToString,
            ),
            'GetLotStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLotStatus,
                    request_deserializer=auction__pb2.GetLotStatusRequest.FromString,
                    response_serializer=auction__pb2.LotStatusResponse.SerializeToString,
            ),
            'JoinAuction': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinAuction,
                    request_deserializer=auction__pb2.LotIdUserRequest.FromString,
                    response_serializer=auction__pb2.Empty.SerializeToString,
            ),
            'LeaveAuction': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveAuction,
                    request_deserializer=auction__pb2.LotIdUserRequest.FromString,
                    response_serializer=auction__pb2.Empty.SerializeToString,
            ),
            'GetWinningsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWinningsByUser,
                    request_deserializer=auction__pb2.UserRequest.FromString,
                    response_serializer=auction__pb2.WinningsList.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=auction__pb2.AuthRequest.FromString,
                    response_serializer=auction__pb2.AuthResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=auction__pb2.AuthRequest.FromString,
                    response_serializer=auction__pb2.AuthResponse.SerializeToString,
            ),
            'GetBidsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBidsByUser,
                    request_deserializer=auction__pb2.UserRequest.FromString,
                    response_serializer=auction__pb2.BidsList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auction.AuctionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auction.AuctionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuctionService(object):
    """------------------------------------
    2. СЕРВІС
    ------------------------------------

    """

    @staticmethod
    def GetAuctions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/GetAuctions',
            auction__pb2.Empty.SerializeToString,
            auction__pb2.AuctionLots.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateLot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/CreateLot',
            auction__pb2.CreateLotRequest.SerializeToString,
            auction__pb2.AuctionLot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/PlaceBid',
            auction__pb2.PlaceBidRequest.SerializeToString,
            auction__pb2.AuctionLot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/DeleteLot',
            auction__pb2.DeleteLotRequest.SerializeToString,
            auction__pb2.DeleteLotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLotStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/GetLotStatus',
            auction__pb2.GetLotStatusRequest.SerializeToString,
            auction__pb2.LotStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/JoinAuction',
            auction__pb2.LotIdUserRequest.SerializeToString,
            auction__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/LeaveAuction',
            auction__pb2.LotIdUserRequest.SerializeToString,
            auction__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWinningsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/GetWinningsByUser',
            auction__pb2.UserRequest.SerializeToString,
            auction__pb2.WinningsList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/Register',
            auction__pb2.AuthRequest.SerializeToString,
            auction__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/Login',
            auction__pb2.AuthRequest.SerializeToString,
            auction__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBidsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/GetBidsByUser',
            auction__pb2.UserRequest.SerializeToString,
            auction__pb2.BidsList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
